services:
  backend:
    build: ./SP-backend
    container_name: sp_backend
    volumes:
      - ./SP-backend:/var/www
      - backend_storage:/var/www/storage
    ports:
      - "9000:8000"
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build: ./SP-frontend
    container_name: sp_frontend
    ports:
      - "3000:80"

  mysql:
    image: mysql:8.0
    container_name: sp_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  backend_storage:
